# Generated by Django 3.1.3 on 2024-08-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_auto_20240830_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
    ]
